# Generated by Django 4.2.30 on 2026-06-21 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0039_alter_ticketchange_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], db_index=True, default='incoming', max_length=10, verbose_name='Direction')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('ignored', 'Ignored'), ('deferred', 'Deferred')], db_index=True, default='success', max_length=10, verbose_name='Status')),
                ('error_type', models.CharField(choices=[('none', 'None'), ('auth', 'Authentication'), ('connection', 'Connection'), ('ssl', 'SSL/TLS'), ('parse', 'Parse'), ('attachment', 'Attachment'), ('bounce', 'Bounce'), ('smtp', 'SMTP'), ('unknown', 'Unknown')], db_index=True, default='none', max_length=20, verbose_name='Error Type')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Message ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('sender', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Sender')),
                ('recipient', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Recipient')),
                ('is_bounce', models.BooleanField(db_index=True, default=False, verbose_name='Is Bounce')),
                ('bounce_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bounce Reason')),
                ('attachment_count', models.PositiveIntegerField(default=0, verbose_name='Attachment Count')),
                ('attachment_errors', models.TextField(blank=True, null=True, verbose_name='Attachment Errors')),
                ('raw_message_excerpt', models.TextField(blank=True, help_text='First portion of the raw message for debugging purposes.', null=True, verbose_name='Raw Message Excerpt')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='helpdesk.queue', verbose_name='Queue')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['direction', 'status', '-timestamp'], name='helpdesk_em_directi_52e119_idx'), models.Index(fields=['error_type', '-timestamp'], name='helpdesk_em_error_t_84e3bf_idx'), models.Index(fields=['queue', 'direction', '-timestamp'], name='helpdesk_em_queue_i_3072b4_idx')],
            },
        ),
    ]
