# Generated by Django 5.2.13 on 2026-06-11 18:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0039_alter_ticketchange_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short name to help users identify this macro. Not shown to ticket submitters.', max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of when to use this macro.', null=True, verbose_name='Description')),
                ('body', models.TextField(help_text='The template body. You can use variables like {{ ticket.title }}, {{ ticket.submitter_email }}, {{ queue.title }}, {{ user.username }}, {{ submitter_name }}, etc. The full ticket context is available.', verbose_name='Body')),
                ('is_shared', models.BooleanField(default=False, help_text='If checked, this macro will be visible to all staff members of the associated queues. If unchecked, only you can see and use it.', verbose_name='Is Shared')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', help_text='Current status of the macro.', max_length=20, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False, help_text='How many times this macro has been used.', verbose_name='Usage Count')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_macros', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('queues', models.ManyToManyField(blank=True, help_text='Select which queues this macro is available for. Leave blank to make it available for all queues.', related_name='macros', to='helpdesk.queue')),
            ],
            options={
                'verbose_name': 'Macro',
                'verbose_name_plural': 'Macros',
                'ordering': ('-modified', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MacroUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macro_name', models.CharField(help_text='Snapshot of the macro name at time of use.', max_length=100, verbose_name='Macro Name')),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Used at')),
                ('rendered_body', models.TextField(blank=True, help_text='The body of the macro after variable substitution.', null=True, verbose_name='Rendered Body')),
                ('context_snapshot', models.JSONField(blank=True, default=dict, help_text='A snapshot of the template context variables used when rendering this macro. Useful for debugging and auditing.', verbose_name='Context Snapshot')),
                ('macro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='helpdesk.macro', verbose_name='Macro')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macro_usages', to='helpdesk.ticket', verbose_name='Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macro_usages', to=settings.AUTH_USER_MODEL, verbose_name='Used by')),
            ],
            options={
                'verbose_name': 'Macro Usage',
                'verbose_name_plural': 'Macro Usages',
                'ordering': ('-used_at',),
            },
        ),
        migrations.CreateModel(
            name='ReplyDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the draft.', max_length=200, null=True, verbose_name='Title')),
                ('body', models.TextField(help_text='The draft reply content.', verbose_name='Body')),
                ('new_status', models.IntegerField(blank=True, help_text='The ticket status to set when this draft is submitted.', null=True, verbose_name='New Status')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('submitted', 'Submitted'), ('discarded', 'Discarded')], default='draft', help_text='Current status of the draft.', max_length=20, verbose_name='Status')),
                ('public', models.BooleanField(default=True, help_text='Whether the follow-up created from this draft will be visible to the ticket submitter.', verbose_name='Public')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('submitted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Submitted at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('macro', models.ForeignKey(blank=True, help_text='The macro this draft was created from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='helpdesk.macro', verbose_name='Source Macro')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_drafts', to='helpdesk.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Reply Draft',
                'verbose_name_plural': 'Reply Drafts',
                'ordering': ('-modified',),
            },
        ),
        migrations.AddIndex(
            model_name='macro',
            index=models.Index(fields=['is_shared', 'status'], name='helpdesk_ma_is_shar_bdf3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='macro',
            index=models.Index(fields=['author', 'is_shared'], name='helpdesk_ma_author__7e9c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='macrousage',
            index=models.Index(fields=['macro', 'used_at'], name='helpdesk_ma_macro_i_fde303_idx'),
        ),
        migrations.AddIndex(
            model_name='macrousage',
            index=models.Index(fields=['user', 'used_at'], name='helpdesk_ma_user_id_4c21f5_idx'),
        ),
        migrations.AddIndex(
            model_name='macrousage',
            index=models.Index(fields=['ticket', 'used_at'], name='helpdesk_ma_ticket__57f8a7_idx'),
        ),
        migrations.AddIndex(
            model_name='replydraft',
            index=models.Index(fields=['ticket', 'status'], name='helpdesk_re_ticket__85051a_idx'),
        ),
        migrations.AddIndex(
            model_name='replydraft',
            index=models.Index(fields=['author', 'status'], name='helpdesk_re_author__034f99_idx'),
        ),
        migrations.AddIndex(
            model_name='replydraft',
            index=models.Index(fields=['author', 'ticket'], name='helpdesk_re_author__f4804a_idx'),
        ),
    ]
