# Generated by Django 5.2.13 on 2026-06-11 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0039_alter_ticketchange_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRoutingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A descriptive name for this routing rule.', max_length=100, verbose_name='Rule Name')),
                ('order', models.IntegerField(db_index=True, default=0, help_text='Lower numbers are evaluated first. The first matching rule is applied.', verbose_name='Priority Order')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this rule is active.', verbose_name='Enabled')),
                ('sender_email', models.CharField(blank=True, help_text='Sender email pattern. Leave blank to match any sender. Supports wildcards (*) in wildcard mode.', max_length=255, verbose_name='Sender E-Mail')),
                ('sender_match_type', models.CharField(choices=[('exact', 'Exact Match'), ('contains', 'Contains'), ('regex', 'Regular Expression'), ('wildcard', 'Wildcard (*)')], default='wildcard', max_length=20, verbose_name='Sender Match Type')),
                ('subject', models.CharField(blank=True, help_text='Subject pattern. Leave blank to match any subject.', max_length=255, verbose_name='Subject Pattern')),
                ('subject_match_type', models.CharField(choices=[('exact', 'Exact Match'), ('contains', 'Contains'), ('regex', 'Regular Expression'), ('wildcard', 'Wildcard (*)')], default='contains', max_length=20, verbose_name='Subject Match Type')),
                ('keywords', models.TextField(blank=True, help_text='Comma or newline-separated keywords to search for in the email body. Leave blank to match any body content.', verbose_name='Keywords')),
                ('keywords_logic', models.CharField(choices=[('all', 'All Keywords'), ('any', 'Any Keyword')], default='any', help_text='Whether all keywords must be present, or just any one of them.', max_length=10, verbose_name='Keywords Logic')),
                ('keywords_match_type', models.CharField(choices=[('exact', 'Exact Match'), ('contains', 'Contains'), ('regex', 'Regular Expression'), ('wildcard', 'Wildcard (*)')], default='contains', max_length=20, verbose_name='Keywords Match Type')),
                ('target_priority', models.IntegerField(blank=True, choices=[(1, '1. Critical'), (2, '2. High'), (3, '3. Normal'), (4, '4. Low'), (5, '5. Very Low')], help_text='Priority to assign. Leave blank to keep default/email-derived priority.', null=True, verbose_name='Target Priority')),
                ('bypass', models.BooleanField(default=False, help_text='If ticked, matching emails will be kept in the mailbox and NOT turned into tickets. Takes precedence over target_* fields.', verbose_name='Bypass Processing')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('queues', models.ManyToManyField(blank=True, help_text='Leave blank for this rule to apply to all queues, or select specific queues to limit this rule to.', related_name='routing_rules', to='helpdesk.queue')),
                ('target_owner', models.ForeignKey(blank=True, help_text='Owner to assign. Leave blank to leave unassigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Target Owner')),
                ('target_queue', models.ForeignKey(blank=True, help_text='Queue to assign to matching tickets. Leave blank to keep the original queue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='helpdesk.queue', verbose_name='Target Queue')),
            ],
            options={
                'verbose_name': 'E-Mail Routing Rule',
                'verbose_name_plural': 'E-Mail Routing Rules',
                'ordering': ('order', 'id'),
            },
        ),
    ]
