# Generated by Django 4.2.30 on 2026-06-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0040_add_email_log_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='error_code',
            field=models.CharField(blank=True, db_index=True, help_text='Protocol-specific error code, e.g. SMTP 550, IMAP NO, etc.', max_length=50, null=True, verbose_name='Error Code'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='fetch_type',
            field=models.CharField(choices=[('poll', 'Polling (Scheduled)'), ('event', 'Event Triggered'), ('manual', 'Manual Trigger')], db_index=True, default='poll', help_text='How the email was fetched: scheduled polling, event-triggered, or manual', max_length=10, verbose_name='Fetch Type'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='protocol',
            field=models.CharField(choices=[('pop3', 'POP3'), ('imap', 'IMAP'), ('imap_oauth', 'IMAP OAuth'), ('smtp', 'SMTP'), ('local', 'Local Directory'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Email protocol used (IMAP, POP3, SMTP, etc.)', max_length=20, verbose_name='Protocol'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['protocol', 'status', '-timestamp'], name='helpdesk_em_protoco_7b94bb_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['error_code', '-timestamp'], name='helpdesk_em_error_c_dd00f3_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['fetch_type', '-timestamp'], name='helpdesk_em_fetch_t_735974_idx'),
        ),
    ]
