# Generated by Django 4.2.30 on 2026-06-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0041_add_protocol_errorcode_fetchtype_to_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='cc',
            field=models.TextField(blank=True, help_text='CC recipient addresses from email headers', null=True, verbose_name='CC Recipients'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='error_code_category',
            field=models.CharField(choices=[('smtp', 'SMTP Status Code (4xx/5xx)'), ('imap', 'IMAP Response Code (NO/BAD/BYE)'), ('pop3', 'POP3 Response Code (ERR)'), ('http', 'HTTP Status Code'), ('ssl', 'SSL/TLS Error Code'), ('dns', 'DNS Resolution Error'), ('custom', 'Custom Enumeration'), ('unknown', 'Unknown/Unclassified')], db_index=True, default='unknown', help_text='Category of the error code: SMTP, IMAP, HTTP, SSL, DNS, custom enumeration, etc.', max_length=20, verbose_name='Error Code Category'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='reply_to',
            field=models.CharField(blank=True, help_text='Reply-To address(es) from email headers', max_length=512, null=True, verbose_name='Reply-To'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['error_code_category', '-timestamp'], name='helpdesk_em_error_c_0e9d7e_idx'),
        ),
    ]
